apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    tier: backend
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: php
    tier: backend
status:
  loadBalancer: {}
